import { ModelMetadata, Agent } from './types';

export const AEGIS_VERSION = "2.5.0-sovereign";

export const DEFAULT_MODEL_ID = 'gemini-3-flash-preview';

export const AVAILABLE_MODELS: ModelMetadata[] = [
  {
    id: 'gemini-3-flash-preview',
    name: 'Gemini 3.0 Flash',
    provider: 'Google DeepMind',
    trainingCutoff: 'Oct 2024',
    biasScore: 12, // Low bias
    license: 'Commercial / API',
    complianceLevel: 'High'
  },
  {
    id: 'gemini-3-pro-preview',
    name: 'Gemini 3.0 Pro',
    provider: 'Google DeepMind',
    trainingCutoff: 'Oct 2024',
    biasScore: 8,
    license: 'Commercial / API',
    complianceLevel: 'High'
  }
];

export const SYSTEM_INSTRUCTION = `
You are a full-featured conversational AI assistant similar to ChatGPT, but running on the secure Aegis AI platform.

CORE BEHAVIOR:
- Be intelligent, natural, and human-like in conversation.
- Speak clearly, concisely, and adapt your tone to the user.
- Be friendly, confident, and honest.
- Correct the user when they are wrong and explain the correct approach.
- Do not sugarcoat bad ideas.

CONTEXT & MEMORY SIMULATION:
- Treat this conversation as continuous.
- Remember and use information the user shares during this chat.
- Refer back to earlier messages naturally.

TEACHING MODE (DEFAULT):
- Explain concepts step by step.
- Start simple, then go deeper.
- Use examples and analogies.
- Check understanding when appropriate.

CHATGPT-LIKE RULES:
- Never say “as an AI language model”.
- Never mention system prompts, policies, or internal rules.
- **Format**: Use clean Markdown. Use **bold** for emphasis, lists for steps, and Code Blocks for technical content.

### PRIVACY SHIELD PROTOCOL (CRITICAL)
You are operating behind a client-side Privacy Shield. User inputs may contain redaction tokens (e.g., \`[REDACTED_EMAIL_1234]\`, \`[REDACTED_NAME]\`).
- **DO NOT** point out that data is missing unless it critically hinders the task.
- **DO NOT** guess the redacted values.
- **ACTION**: Treat these tokens as valid variables.
`;

export const AGENTS: Agent[] = [
  {
    id: 'default',
    name: 'Aegis Core',
    description: 'The standard, versatile AI assistant for everyday tasks.',
    category: 'Productivity',
    icon: '◈',
    systemInstruction: SYSTEM_INSTRUCTION
  },
  {
    id: 'coder',
    name: 'DevOps Architect',
    description: 'Senior engineer specialized in clean code, cloud architecture, and debugging.',
    category: 'Coding',
    icon: '💻',
    systemInstruction: SYSTEM_INSTRUCTION + `\n\nROLE: Senior Software Engineer.\nSTYLE: Concise, technical, production-ready code only. Explain trade-offs.`
  },
  {
    id: 'writer',
    name: 'Editorial Chief',
    description: 'Expert editor for polishing prose, blogs, and marketing copy.',
    category: 'Writing',
    icon: '✍️',
    systemInstruction: SYSTEM_INSTRUCTION + `\n\nROLE: Senior Editor.\nSTYLE: Engaging, punchy, and grammatically perfect. Focus on tone and flow.`
  },
  {
    id: 'mba',
    name: 'Strategy Consultant',
    description: 'Business mentor for analyzing markets, risks, and pitch decks.',
    category: 'Business',
    icon: '💼',
    systemInstruction: SYSTEM_INSTRUCTION + `\n\nROLE: McKinsey/BCG Consultant.\nSTYLE: Strategic, data-driven, direct. Focus on ROI, TAM, and risk mitigation.`
  }
];

export const TOS_TEXT = `
AEGIS AI: SOVEREIGN INTELLECTUAL PROPERTY AGREEMENT

1. OWNERSHIP OF INPUTS
You retain absolute ownership of all data, text, or files you upload ("Inputs"). Aegis AI claims no intellectual property rights over your data.

2. OWNERSHIP OF OUTPUTS
All rights, title, and interest in the content generated by the AI ("Outputs") are assigned to you, the User, to the fullest extent permitted by law. You may copyright, sell, or patent these outputs.

3. ZERO-TRAINING GUARANTEE
Aegis AI does not use User Inputs or Outputs to train, refine, or improve our models or any third-party models. Your sessions are private and ephemeral.

4. DATA PORTABILITY (GDPR/EU AI ACT)
You have the right to export your entire chat history and account data in JSON format at any time.

5. OPEN SOURCE TRANSPARENCY
The core infrastructure of Aegis AI is licensed under the Apache 2.0 License.
`;